name: Release Media Archives
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Upload archives as release assets
        id: upload
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v0.1
          name: v0.1
          body_path: RELEASE_NOTES.md
          files: |
            client/public/assets/.local/uploads/flyers.tar.gz
            client/public/assets/.local/uploads/gallery-freakfest.tar.gz
            client/public/assets/.local/uploads/venue.tar.gz
