name: Release Media Archives
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Create release v0.1 and upload archives
        uses: softprops/action-gh-release@v2
        with:
          files: |
            client/public/assets/.local/uploads/flyers.tar.gz
            client/public/assets/.local/uploads/gallery-freakfest.tar.gz
            client/public/assets/.local/uploads/venue.tar.gz
